baseURL = "/wirpv2/"
languageCode = "en-us"
title = "radical // education"

# Use absolute URLs for deployed website
relativeURLs = false
canonifyURLs = true

# Disable taxonomies, sitemap, and RSS generation
disableKinds = ["taxonomy", "term", "sitemap", "RSS"]

[params]
  description = "Critical thinking for radical change"
  author = "radical // education"

[markup.goldmark.renderer]
  unsafe = true
